name: Unit Tests

on: [push, pull_request]

jobs:

  luaunit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup ‘lua’
      uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: 5.3
    - name: Setup ‘luarocks’
      uses: leafo/gh-actions-luarocks@v4
    - name: Setup ‘luaunit’
      run: |
        luarocks install cluacov
        luarocks install luaunit
    - name: Run unit tests
      run: |
        lua -lluacov ./tests/test.lua -v
        luacov
